const perigos = [
  "EXPOSICAO_HIDRICA",
  "TRAFEGABILIDADE",
  "INSTABILIDADE",
  "INCENDIO",
  "TEMPESTADES",
];
const pesos = {
  EXPOSICAO_HIDRICA: 0.3,
  TRAFEGABILIDADE: 0.25,
  INSTABILIDADE: 0.2,
  INCENDIO: 0.15,
  TEMPESTADES: 0.1,
};
const agregacao90d = {
  inicio: "2026-05-03",
  fim: "2026-07-31",
  severidade: 0,
  frequencia: 0,
  duracao: 0,
  recorrencia: 0,
  indice_agregado: 0,
  classificacao: "NORMAL",
  quantidade_dias_relevantes: 0,
  quantidade_eventos: 0,
  maior_duracao_evento: 0,
  cobertura_percentual: 100,
};
const provenienciaNasa = {
  fonte_meteorologica: "NASA_POWER",
  dataset_meteorologico: "NASA POWER Daily Point",
  parametro_vento: "WS2M",
  altura_vento_m: 2,
  unidade_vento: "m/s",
  agregacao_temporal_vento: "media_diaria",
};
export const fixtureExposicao = {
  id_fazenda: "1",
  politica_id: "AGRISHIELD-EQUIP-v1.0",
  metodologia: "APRESENTACAO_EXPOSICAO_MAQUINARIO_MVP_V1",
  metodologia_score: "SCORE_V1",
  metodologia_comparacao: "COMPARACAO_90D_V1",
  data_referencia: "2026-07-31",
  fonte_meteorologica: "NASA_POWER",
  fazenda: {
    nome: "Fazenda Boa Esperança",
    cidade: "Sorriso",
    uf: "MT",
    area_ha: 250,
    latitude: -12.545,
    longitude: -55.721,
  },
  contexto_territorial: {
    declividade_media_graus: 3.218681,
    posicao_topografica_relativa_m: -1.45721,
    distancia_drenagem_m: 2001.6526,
    area_montante_km2: 850.3291,
  },
  fontes_avaliacao: [
    {
      fonte: "NASA_POWER",
      nome_exibicao: "NASA POWER",
      status: "USADA",
      categoria: "METEOROLOGIA",
      contribui_score: true,
      indicadores: ["Precipitação", "Temperatura", "Umidade relativa", "Vento"],
      descricao: "Meteorologia histórica usada nesta avaliação.",
    },
    {
      fonte: "OPEN_METEO",
      nome_exibicao: "Open-Meteo",
      status: "DISPONIVEL",
      categoria: "METEOROLOGIA",
      contribui_score: false,
      indicadores: ["Precipitação", "Temperatura", "Umidade relativa", "Vento"],
      descricao:
        "Fonte meteorológica alternativa. Não utilizada nesta avaliação.",
    },
    {
      fonte: "SRTM",
      nome_exibicao: "SRTM",
      status: "USADA",
      categoria: "TERRITORIO",
      contribui_score: true,
      indicadores: [
        "Declividade média",
        "Posição topográfica relativa",
        "Instabilidade",
        "Exposição Hídrica",
      ],
      descricao:
        "Relevo usado em Instabilidade e na suscetibilidade territorial da Exposição Hídrica.",
    },
    {
      fonte: "MERIT_HYDRO",
      nome_exibicao: "MERIT Hydro",
      status: "USADA",
      categoria: "TERRITORIO",
      contribui_score: true,
      indicadores: [
        "Distância à drenagem",
        "Área montante",
        "Exposição Hídrica",
      ],
      descricao:
        "Drenagem e área montante usadas na suscetibilidade territorial da Exposição Hídrica.",
    },
  ],
  integracoes: [
    {
      fonte: "MAPBIOMAS",
      nome_exibicao: "MapBiomas",
      status: "DISPONIVEL",
      contribui_score: false,
      descricao: "Uso e cobertura do solo; não participa do score atual.",
    },
    {
      fonte: "INMET",
      nome_exibicao: "INMET",
      status: "NAO_UTILIZADO",
      contribui_score: false,
      descricao: "Integração disponível, mas não usada nesta avaliação.",
    },
  ],
  exposicao_hidrica: {
    proximidade_drenagem: 48.28,
    relevancia_area_montante: 55.58,
    posicao_topografica: 65.84,
    suscetibilidade_territorial: 55.24,
    janela_anterior: {
      inicio: "2026-02-02",
      fim: "2026-05-02",
      indice: 20,
      classificacao: "NORMAL",
      quantidade_dias_relevantes: 1,
      quantidade_eventos: 1,
      cobertura_percentual: 100,
    },
    janela_atual: {
      inicio: "2026-05-03",
      fim: "2026-07-31",
      indice: 0,
      classificacao: "NORMAL",
      quantidade_dias_relevantes: 0,
      quantidade_eventos: 0,
      cobertura_percentual: 100,
    },
    metodologia:
      "EXPOSICAO_HIDRICA_METEOROLOGICA_COM_SUSCETIBILIDADE_TERRITORIAL_T3_G3",
    calibrado_contra_sinistros: false,
  },
  detalhes_perigos: {
    trafegabilidade: {
      perigo: "TRAFEGABILIDADE",
      dia_maior_indice: {
        data: "2026-07-21",
        precipitacao_d0: 40,
        acumulado_3d: 60,
        dias_desde_ultima_chuva_relevante: 0,
        componente_dia: 44.69,
        componente_acumulado: 59.18,
        componente_recuperacao: 59.18,
        indice_diario: 52.36,
      },
      agregacao_90d: { ...agregacao90d },
      proveniencia: {
        fonte_meteorologica: "NASA_POWER",
        dataset_meteorologico: "NASA POWER Daily Point",
      },
      peso_dia: 0.35,
      peso_acumulado: 0.45,
      peso_recuperacao: 0.2,
      limiar_relevancia: 25,
      metodologia:
        "COMPOSICAO_METEOROLOGICA_PROPRIA_DIA_ACUMULADO_RECUPERACAO_V1",
      aviso_metodologia:
        "Metodologia experimental, ainda não calibrada contra sinistros ou dados reais de operação de máquinas.",
    },
    incendio: {
      perigo: "INCENDIO",
      dia_maior_indice: {
        data: "2026-07-24",
        temperatura_maxima_c: 30,
        umidade_relativa_media_pct: 60,
        velocidade_vento_media_m_s: 2,
        dias_desde_ultima_chuva: 4,
        componente_temperatura: 0.6,
        componente_baixa_umidade: 0.125,
        componente_vento: 0.2,
        indice_base: 24.662,
        multiplicador_secura: 1.05,
        indice_diario: 23.456,
        motivo: "SECURA_ANTECEDENTE_APLICADA",
      },
      agregacao_90d: { ...agregacao90d },
      proveniencia: { ...provenienciaNasa },
      metodologia: "PROXY_METEOROLOGICO_PROPAGACAO_FOGO",
    },
    instabilidade: {
      perigo: "INSTABILIDADE",
      dia_maior_indice: {
        data: "2026-07-22",
        declividade_media_graus: 7.7,
        suscetibilidade_topografica: 25.8,
        condicao_hidrica_meteorologica: 50,
        fator_ativacao: 0.65,
        indice_diario: 16.77,
        motivo: "ATIVACAO_HIDRICA_APLICADA",
      },
      agregacao_90d: { ...agregacao90d },
      proveniencia: {
        fonte_meteorologica: "NASA_POWER",
        dataset_meteorologico: "NASA POWER Daily Point",
        parametro_vento: null,
        altura_vento_m: null,
        unidade_vento: null,
        agregacao_temporal_vento: null,
      },
      fonte_declividade: "SRTM",
      dataset_declividade: "USGS/SRTMGL1_003",
      posicao_topografica_relativa_m: -1.45721,
      posicao_topografica_participa_formula: false,
      metodologia: "SUSCETIBILIDADE_TOPOGRAFICA_X_ATIVACAO_HIDRICA_TEMPORAL",
    },
    tempestades: {
      perigo: "TEMPESTADES",
      dia_maior_indice: {
        data: "2026-07-20",
        velocidade_vento_media_m_s: 2,
        precipitacao_diaria_mm: 10,
        componente_vento: 0.2,
        componente_chuva: 0.2,
        indice_vento: 20,
        fator_combinado_vento_chuva: 0.8,
        indice_diario: 16,
        motivo: "AMPLIFICACAO_CHUVA_APLICADA",
      },
      agregacao_90d: { ...agregacao90d },
      proveniencia: { ...provenienciaNasa },
      metodologia: "PROXY_METEOROLOGICO_TEMPESTADE",
    },
  },
  score_atual: 0,
  classificacao_atual: "NORMAL",
  score_anterior: 17.165714,
  classificacao_anterior: "NORMAL",
  variacao_pontos: -17.165714,
  variacao_percentual: -100,
  direcao_variacao: "REDUCAO",
  perigo_dominante: null,
  perigos_dominantes: [
    "EXPOSICAO_HIDRICA",
    "INSTABILIDADE",
    "INCENDIO",
    "TEMPESTADES",
  ],
  perigos: perigos.map((perigo) => ({
    perigo,
    indice: 0,
    classificacao: "NORMAL",
    participa_score: true,
    elegivel: true,
    peso: pesos[perigo],
    contribuicao: 0,
    cobertura_percentual: 100,
    qualidade_suficiente: true,
    estado: "PARTICIPANTE_ELEGIVEL",
    motivo_nao_contribuicao: null,
    motivos_indisponibilidade: [],
    metodologia: "PERIGO_ATUAL",
  })),
  timeline_eventos: [],
  qualidade_dados: {
    conceito: "COBERTURA_E_QUALIDADE_DOS_DADOS",
    coberturas_por_perigo: perigos.map((perigo) => ({
      perigo,
      cobertura_percentual: 100,
      qualidade_suficiente: true,
    })),
    warmup_completo: true,
    dias_contexto_esperados: 180,
    dias_contexto_disponiveis: 180,
    quantidade_gaps: 0,
    dias_com_dados_ausentes: 0,
    fonte_meteorologica: "NASA_POWER",
    periodo_aquisicao: {
      inicio: "2026-02-02",
      fim: "2026-07-31",
      dias_esperados: 180,
      finalidade: "AQUISICAO",
    },
  },
  score_anterior_publicavel: true,
  score_publicavel: true,
  comparacao_publicavel: true,
  avaliacao_publicavel: true,
  avisos_metodologicos: ["Resultado demonstrativo."],
  disclaimer: "Não representa probabilidade atuarial de sinistro.",
  disclaimer_comparacao: "Comparação demonstrativa.",
  versao: "exposicao-apresentacao-mvp",
};
