export const DEMO_FAZENDAS = [
  {
    id: "1",
    id_fazenda: "1",
    nome_fazenda: "Fazenda Boa Esperança",
    numero_apolice: "1234567890",
    cep: "78890-000",
    cidade: "Sorriso",
    uf: "MT",
    tipo_operacao: "campo",
    proximidade_agua: true,
    latitude: -12.545,
    longitude: -55.721,
    area_ha: 350,
    status_geoespacial: "SUCESSO",
  },
  {
    id: "2",
    id_fazenda: "2",
    nome_fazenda: "Fazenda Santa Luzia",
    numero_apolice: "2233445566",
    cep: "78550-000",
    cidade: "Sinop",
    uf: "MT",
    tipo_operacao: "transporte",
    proximidade_agua: false,
    latitude: -11.8644,
    longitude: -55.5025,
    area_ha: 420,
    status_geoespacial: "SUCESSO",
  },
  {
    id: "3",
    id_fazenda: "3",
    nome_fazenda: "Fazenda Três Rios",
    numero_apolice: "9988776655",
    cep: "78700-000",
    cidade: "Rondonópolis",
    uf: "MT",
    tipo_operacao: "campo",
    proximidade_agua: true,
    latitude: -16.4708,
    longitude: -54.6356,
    area_ha: 280,
    status_geoespacial: "SUCESSO",
  },
];

export const DEMO_DASH = {
  score: {
    score: 78,
    condicao_atual: "RESTRIÇÃO",
    data_referencia: "2025-05-12",
    origem_dados: "demo",
    fazenda: {
      nome: "Fazenda Boa Esperança",
      apolice: "1234567890",
      cidade: "Sorriso",
      uf: "MT",
      tipo_operacao: "campo",
    },
    distribuicao_30d: { ideais: 18, atencao: 7, restricao: 5, total: 30 },
    fatores_risco: [
      {
        fator: "Chuva acumulada (7 dias)",
        detalhe: "92 mm nos últimos 7 dias",
        impacto: "Alto impacto",
        pontos: 30,
      },
      {
        fator: "Umidade do solo",
        detalhe: "Solo encharcado",
        impacto: "Alto impacto",
        pontos: 28,
      },
      {
        fator: "Proximidade de áreas alagáveis",
        detalhe: "Áreas de risco a até 1 km",
        impacto: "Médio impacto",
        pontos: 16,
      },
    ],
    metricas_dia: {
      chuva_acumulada_7d: 92,
      umidade_relativa_pct: 88,
      solo_encharcado: true,
    },
  },
  alertas: [
    {
      tipo: "Chuvas intensas previstas",
      severidade: "Alta",
      detalhe: "34 mm previstos; probabilidade 86%",
      data: "próximos dias",
    },
    {
      tipo: "Solo encharcado",
      severidade: "Média",
      detalhe: "Fazenda Boa Esperança",
      data: "hoje",
    },
    {
      tipo: "Risco de alagamento",
      severidade: "Média",
      detalhe: "Chuva 7d=92 mm; previsão 5d=85 mm",
      data: "próximos 5 dias",
    },
  ],
  previsao_5d: [],
};
